spring.application.name=hub
server.port=8080

# H2 In-Memory DB Setup
spring.datasource.url=jdbc:h2:mem:hubdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Auto-run SQL scripts on startup
spring.sql.init.mode=always